version: '3.0'

services:

  mysql:
    image: mysql:latest
    volumes:
      - /mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
    ports:
      - "3306:3306"
    container_name: mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    environment:
      REDIS_HOST: root
      REDIS_PORT: 6379
      REDIS_PASSWORD: root
      REDIS_USER: root
volumes:
  todo-mysql-data:
  cache:
